[package]
name = "gitlab-warden"
version = "0.1.0"
edition = "2024"
authors = ["Afshin Karimi afshinnkarimi@gmail.com>"]
description = "ğŸ›¡ï¸ A Rust-powered watchdog that monitors GitLab access tokens, tracks expiration dates, and notifies before they expire."
license = "MIT"
repository = "https://github.com/afshinnkarimi/gitlab-warden"
readme = "README.md"

[dependencies]
prometheus = "0.14.0"
serde = { version = "1.0.228", features = ["derive"]}
serde_yaml = "0.9.34"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
